parameters:
#    bacloo_crm.example.class: Bacloo\CrmBundle\Example

services:
#    bacloo_crm.example:
#        class: %bacloo_crm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]