<?php

namespace Bacloo\CrmBundle\Entity;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
}
