services:
    avro_csv.importer:
        class: Avro\CsvBundle\Util\Importer
        arguments: ["@avro_csv.reader", "@event_dispatcher", "@avro_case.converter", "@doctrine.odm.mongodb.document_manager", "%avro_csv.batch_size%"]

    avro_csv.iterator:
        class: Avro\CsvBundle\Doctrine\ODM\Iterator
        arguments: ["@doctrine.odm.mongodb.document_manager"]



