<?php

namespace Bacloo\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
	public function searchfiche($ficheid, $raisonSociale, $nom)
	{
		// On utilise le QueryBuilder créé par le repository directement pour gagner du temps
		// Plus besoin de faire le select() ni le from() par la suite donc
		$qb = $this->createQueryBuilder('f')
					->leftJoin('f.bcontacts', 'c')
					->addSelect('c');
		$qb->where('f.id = :id')
		->setParameter('id', $ficheid);
		if(isset($raisonSociale) and isset($ficheid)){
			$qb->andWhere('f.raisonSociale LIKE :raisonSociale');
		}
		elseif(isset($raisonSociale) and empty($ficheid))
		{
			$qb->orWhere('f.raisonSociale LIKE :raisonSociale');		
		}
		else
		{
			$qb->orWhere('f.raisonSociale = :raisonSociale');		
		}		
		$qb->setParameter('raisonSociale', '%'.$raisonSociale.'%');
		
		if(isset($nom) and isset($ficheid)){
			$qb->andWhere('c.nom LIKE :nom');
		}
		elseif(isset($nom) and empty($ficheid))
		{
			$qb->orWhere('c.nom LIKE :nom');		
		}		
		else
		{
			$qb->orWhere('c.nom = :nom');		
		}		
		$qb->setParameter('nom', '%'.$nom.'%');		
		return $qb->getQuery()
		->getResult();
	}
}
